site_name: JackTrip
repo_url: https://github.com/jacktrip/jacktrip
edit_uri: edit/dev/docs/
plugins:
  - doxygen:
      packages:
        - doxygen:
            url : .
            config : jacktrip_doxygen
nav:
  - Home: index.md
  - User Guide:
    - Installation: Install.md
  - Developer Guide:
    - QMake Build:
      - Linux: Build/Linux.md
      - Mac OS: Build/Mac.md
      - Windows: Build/Windows.md
    - Meson Build: Build/Meson_build.md
    - API: doxygen
    - Development Tools:
      - Formatting: DevTools/Formatting.md
      - Static Analysis: DevTools/StaticAnalysis.md
    - Write Documentation: Documentation/MkDocs.md
  - About:
    - Contributors: About/Contributors.md
    - Resources: About/Resources.md
    - Changelog: About/CHANGELOG.md
    - License: About/License.md
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - admonition

